### ISSUE TITLE
Showing function print problem (No VENDOR & random space)

### ISSUE THREAD

**Issue by Jacopx** [Jacopx/netscanner#1]
If you try to use the showing function (number 3) you'll see all your entry without the vendor name and with some random space between the entries.

**Comment by mooow** [comment]
Problem was that you were using a list type as if it were a dict.
`netscan.py:+88,3` does:
```
...
fr=open(show, 'r')
ip, mac, vend = show_file(fr)
printer(ip, mac, vend)
...
```
`show_file()` returns three lists so ip, mac and vend are all lists.
On file `netf.py:+51,5` there was:
```
for k in mac:
  ...
  ... vend[k] ...
```
since k is an element in mac (that is, a string) you were using a list as a dict. You didn't notice because you are affected by bug #2
[patch.txt](https://github.com/Jacopx/netscanner/files/666337/patch.txt)

**Comment by Jacopx** [comment]
@mooow Thanks, i'll fix it!
